### ISSUE TITLE
[foxy] Small changes hospital world package

### ISSUE THREAD

**Issue by Carlosalpha1** [JdeRobot/CustomRobots#166]
The following changes are required in [./amazon_hospital/hospital_world](https://github.com/JdeRobot/CustomRobots/tree/foxy-devel/amazon_hospital/hospital_world) package:
- In hospital_follow_person.world (where the is a person model) the **initial camera position** in gazebo and **fullscreen**.
- In peson.cpp disabling **auto movement.**

**Comment by jmplaza** [comment]
Fixed in #167
