### ISSUE TITLE
[simple_circuit] Mesh file path not correct

### ISSUE THREAD

**Issue by SakshayMahna** [JdeRobot/CustomRobots#35]
It seems that the model path in the sdf file simple_circuit model is not correct.

https://github.com/JdeRobot/CustomRobots/blob/melodic-devel/f1/simple_circuit/model.sdf

We have `model://simple_circuit_2/meshes/simple_line.dae`. Since we do not have any model by the name of `simple_circuit_2`, it should be changed to `simple_circuit`. 

@igarag Can you please have a look?

**Comment by igarag** [comment]
Sure. I'll handle it.

**Comment by igarag** [comment]
Fixed @SakshayMahna. Sorry for the bug.
