### ISSUE TITLE
[Models] ROS 2 Support for Amazon Robot

### ISSUE THREAD

**Issue by shreyasgokhale** [JdeRobot/CustomRobots#7]
Basic support to launch Amazon Robot model in gazebo with correct state transformer is necessary to launch warehouse exercise. However, ROS2 has significant changes when migrating from ROS1 and for the [gazebo_ros](https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-Migration:-Spawn-and-delete) package. The model representation `.xacro` (`.urdf`) / `.sdf` and launch sequence needs to be updated accordingly.

**Comment by naxvm** [comment]
Pending to fix the non-functional prismatic joint.
