### ISSUE TITLE
[Noetic-devel] f1 car is initialised at a wrong angle

### ISSUE THREAD

**Issue by Suhas-G** [JdeRobot/CustomRobots#70]
This issue is related to the `noetic-devel` branch. When using this branch in Follow line exercise we get the car initialized at a wrong angle.
![image](https://user-images.githubusercontent.com/20943400/114712975-48d72000-9d4e-11eb-924f-a963c574bd96.png)

Apart from this, there are also some warnings about materials not being applied and errors about multiple initiations of service on terminal.
![image](https://user-images.githubusercontent.com/20943400/114713339-a79c9980-9d4e-11eb-8bfd-7c1b5fe9c9cc.png)

**Comment by Suhas-G** [comment]
There are multiple differences between the branches in f1 folder
The files having changes.
![image](https://user-images.githubusercontent.com/20943400/114714076-635dc900-9d4f-11eb-915f-9b668b029906.png)

For example, the `f1/meshes/F1.dae` has extra content about the materials.

Would it be fine to use same meshes from melodic-devel branch?

**Comment by jmplaza** [comment]
sure @Suhas-G . The best and most up-to-date meshes and robot models are in the melodic-devel branch. Feel free to copy everything you need from it

**Comment by fqez** [comment]
Hi @Suhas-G, as far as I know that F1 model is ancient, hence I really don't know the state of it (if it works or it does not). Did you manage to update your models, as @jmplaza stated? Let us know so we can close this issue. Thanks!!

**Comment by sergiopaniego** [comment]
PR merged, issue closed!
