### ISSUE TITLE
Issue with the car1 and car2 models in car-junction

### ISSUE THREAD

**Issue by iamarkaj** [JdeRobot/CustomRobots#84]
I was running the car-junction exercise in **Ubuntu 20.04** and both the cars move upward instead of moving forward. Few more errors can be found [here](https://github.com/JdeRobot/RoboticsAcademy/pull/1051#issue-676222489). I am attaching a video for reference:

https://user-images.githubusercontent.com/40225765/123466533-0fa01380-d60d-11eb-9d9e-6e7f31960ef8.mp4

**Comment by ReyDoran** [comment]
This issue is related to the world launch file and the forces applied in exercise.py. It was solved in Robotics Academy (pr # 1278) and will be included in the upcoming RADI 3.1.7
